### PR TITLE
covered cases in text truncate longest text with wrap on off fixes

### PR DESCRIPTION
**Pull request by ashwinikalokhe**

### CODE REVIEW

**Comment by conniefry** [comment]
Do these test changes correspond to a PR in pxCore?

**Comment by ashwinikalokhe** [comment]
Yes it covers PR 1740 .

**Comment by conniefry** [comment]
You must create a new file, not change an existing one, when the changes are dependent on new work in a pxCore PR.

**Comment by conniefry** [comment]
../tests/text2tests_v2.js is a new test added for pxCore PR 1740

**Pull request merged**
